version: '3'
services:
  gitea:
    image: 'gitea/gitea:1.17.3'
    hostname: "${GITEA}"
    container_name: ${GITEA}
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__DOMAIN=${GITEA}
      - GITEA__server__SSH_DOMAIN=${GITEA}
      - GITEA__server__HTTP_PORT=3000
      - GITEA__server__SSH_LISTEN_PORT=22
      - GITEA__server__SSH_PORT=8022
      - GITEA__server__ROOT_URL=http://${GITEA}:3000
      - ONLY_ALLOW_PUSH_IF_GITEA_ENVIRONMENT_SET=false
    restart: unless-stopped
    ports:
      - '8022:22'
      - '3000:3000'
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://${GITEA}:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./gitea.app.ini:/data/gitea/conf/app.ini

