apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
  namespace: default

spec:
  stripPrefix:
    prefixes:
      - /guestbook
      - /helm-guestbook
      - /kustomize-guestbook
      - /podinfo

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutebar

spec:
  entryPoints:
    - web
  routes:

  - match: PathPrefix(`/guestbook`)
    kind: Rule
    services:
    - name: guestbook-ui
      port: 80
    middlewares:
    - name: stripprefix
      namespace: default

  - match: PathPrefix(`/helm-guestbook`)
    kind: Rule
    services:
    - name: helm-guestbook
      port: 80
    middlewares:
    - name: stripprefix
      namespace: default

  - match: PathPrefix(`/kustomize-guestbook`)
    kind: Rule
    services:
    - name: kustomize-guestbook-ui
      port: 80
    middlewares:
    - name: stripprefix
      namespace: default

  - match: PathPrefix(`/podinfo`)
    kind: Rule
    services:
    - name: podinfo
      port: 9898
    middlewares:
    - name: stripprefix
      namespace: default

